data_method: MyDataMethods.orders_by_client
chart:
  options:
    legend:
      display: false
    scales:
      xAxes:
        - scaleLabel:
            display: true
            labelString: Pedidos
      yAxes:
        - scaleLabel:
            display: true
            labelString: Cliente