measure: order
filters:
  - created_at
dimensions:
  - created_at
chart:
  type: line
  options:
    scales:
      xAxes:
        - scaleLabel:
            display: true
            labelString: Fecha de pedidos
      yAxes:
        - scaleLabel:
            display: true
            labelString: Cantidad de pedidos